version: "3"

services:
  node-app:
    build: .
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "${NODE_ENV}"
    volumes:
      - .:/app
      - /app/node_modules
    command: "${CMD}"
    #env_file:
     # - ./.env

