version: "3"

networks:
  node-app:
    driver: bridge

services:
  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app_server
    ports:
      - 3000:3000
    environment:
      NODE_ENV: "${NODE_ENV}"
    volumes:
      - .:/app
      - /app/node_modules
    command: "${CMD}"
    #env_file:
     # - ./.env
    depends_on:
      - pgsql
    networks:
      - node-app

  pgsql:
      image: postgres:12.3
      container_name: node_app_db
      environment:
        POSTGRES_USER: "${DB_USER}"
        POSTGRES_PASSWORD: "${DB_PASSWORD}"
        POSTGRES_DB: "${DB_DATABASE}"
        SERVICE_TAGS: dev
        SERVICE_NAME: pgsql
      ports:
        - "5432:5432"
      networks:
        - node-app

volumes:
  dbdata:
    driver: local